CREATE TABLE IF NOT EXISTS mainmenu (
id integer PRIMARY KEY AUTOINCREMENT,
title text NOT NULL,
url text NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
id integer PRIMARY KEY AUTOINCREMENT,
passport_number text NOT NULL,
title text NOT NULL,
text text NOT NULL,
institution_name text NOT NULL,
department_name text NOT NULL,
definition text NOT NULL,
typological text NOT NULL,
object_owner text NOT NULL,
author text NOT NULL,
clarified_author text NOT NULL,
object_title NOT NULL,
clarified_object_title NOT NULL,
time_of_creation text NOT NULL,
clarified_time_of_creation text NOT NULL,
material text NOT NULL,
clarified_material text NOT NULL,
technique text NOT NULL,
clarified_technique text NOT NULL,
object_size text NOT NULL,
clarified_size text NOT NULL,
weight text NOT NULL,
clarified_weight text NOT NULL,
reason text NOT NULL,
object_input_date text NOT NULL,
execute_restorer text NOT NULL,
object_output_date text NOT NULL,
responsible_restorer text NOT NULL,
origin_description text NOT NULL,
appearance_description text NOT NULL,
damages_description text NOT NULL,
signs_description text NOT NULL,
size_description text NOT NULL,
purposes_researches text NOT NULL,
methods_researches text NOT NULL,
executor_date_researches text NOT NULL,
results_researches text NOT NULL,
restoration_program text NOT NULL,
treatments_descriptions text NOT NULL,
treatments_chemicals text NOT NULL,
treatments_executor_date text NOT NULL,
treatments_results text NOT NULL,
photo_description TEXT NOT NULL,
photo BLOB NOT NULL,
time integer NOT NULL
);